import React from 'react';
import './index.scss';

const PrivacyPolicyContent = () => {
  return (
    <div className="privacypolicy">
      <div className="privacypolicy__content">
        <h1 className="heading">privacy policy</h1>
        <p className="privacypolicy__subheading">Effective date: July 17, 2019</p>

        <p className="privacypolicy__text">
          VZ Games SIA ("us", "we", or "our") operates the <span>https://www.hashrush.com</span> website and the Hash Rush software application (here in after referred to as the "Service").
        </p>
        <p className="privacypolicy__text">
          This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.
        </p>
        <p className="privacypolicy__text">
          We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
          Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
        </p>

        <span className="privacypolicy__title">Definitions</span>
        <span className="privacypolicy__subtitle">Service</span>
        <p className="privacypolicy__text">
          Service means the <span>https://www.hashrush.com</span> website and Hash Rush software application operated by VZ Games SIA
        </p>

        <span className="privacypolicy__subtitle">Usage Data</span>
        <p className="privacypolicy__text">
          Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
        </p>

        <span className="privacypolicy__subtitle">cookies</span>
        <p className="privacypolicy__text">Cookies are small files stored on your device (computer or mobile device).</p>

        <span className="privacypolicy__subtitle">Data Controller</span>
        <p className="privacypolicy__text">
          Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines
          the purposes for which and the manner in which any personal information are, or are to be, processed.
          For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
        </p>

        <span className="privacypolicy__subtitle">Data Processors (or Service Providers)</span>
        <p className="privacypolicy__text">
          Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.
        </p>

        <span className="privacypolicy__subtitle">Data Subject (or User)</span>
        <p className="privacypolicy__text">
          Data Subject is any living individual who is using our Service and is the subject of Personal Data.
        </p>

        <span className="privacypolicy__title">Information Collection and Use</span>
        <p className="privacypolicy__text">
          We collect several different types of information for various purposes to provide and improve our Service to you.
        </p>
        <span className="privacypolicy__posttitle">Types of Data Collected</span>
        <span className="privacypolicy__subtitle">Personal Data</span>
        <p className="privacypolicy__text">
          While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
        </p>

        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item">Email address</li>
          <li className="privacypolicy__list-item">First name and last name</li>
          <li className="privacypolicy__list-item">Cookies and Usage Data</li>
        </ul>

        <p className="privacypolicy__text">
          We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you.
          You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.
        </p>

        <span className="privacypolicy__subtitle">Usage Data</span>
        <p className="privacypolicy__text">
          We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
        </p>
        <p className="privacypolicy__text">
          This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that
          you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p className="privacypolicy__text">
          When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID,
          the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
        </p>

        <span className="privacypolicy__subtitle">Tracking &amp; Cookies Data</span>
        <p className="privacypolicy__text">
          We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
        </p>
        <p className="privacypolicy__text">
          Cookies are files with a small amount of data which may include an anonymous unique identifier.
          Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, 
          tags and scripts to collect and track information and to improve and analyse our Service.
        </p>
        <p className="privacypolicy__text">
          You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>

        <span className="privacypolicy__subtitle">Examples of Cookies we use:</span>

        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item"><span>Session Cookies. </span>We use Session Cookies to operate our Service.</li>
          <li className="privacypolicy__list-item"><span>Preference Cookies. </span>We use Preference Cookies to remember your preferences and various settings.</li>
          <li className="privacypolicy__list-item"><span>Security Cookies. </span>Security Cookies. We use Security Cookies for security purposes.</li>
        </ul>
      </div>
    </div>
  );
};

export default PrivacyPolicyContent;