import React from 'react';
import './index.scss';

const PrivacyPolicyContent = () => {
  return (
    <div className="privacypolicy">
      <div className="privacypolicy__content">
        <h1 className="heading">privacy policy</h1>
        <p className="privacypolicy__subheading">Effective date: July 17, 2019</p>

        <p className="privacypolicy__text">
          VZ Games SIA ("us", "we", or "our") operates the <span>https://www.hashrush.com</span> website and the Hash Rush software application (here in after referred to as the "Service").
        </p>
        <p className="privacypolicy__text">
          This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.
        </p>
        <p className="privacypolicy__text">
          We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
          Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
        </p>

        <span className="privacypolicy__title">Definitions</span>
        <span className="privacypolicy__subtitle">Service</span>
        <p className="privacypolicy__text">
          Service means the <span>https://www.hashrush.com</span> website and Hash Rush software application operated by VZ Games SIA
        </p>

        <span className="privacypolicy__subtitle">Usage Data</span>
        <p className="privacypolicy__text">
          Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
        </p>

        <span className="privacypolicy__subtitle">cookies</span>
        <p className="privacypolicy__text">Cookies are small files stored on your device (computer or mobile device).</p>

        <span className="privacypolicy__subtitle">Data Controller</span>
        <p className="privacypolicy__text">
          Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines
          the purposes for which and the manner in which any personal information are, or are to be, processed.
          For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
        </p>

        <span className="privacypolicy__subtitle">Data Processors (or Service Providers)</span>
        <p className="privacypolicy__text">
          Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.
        </p>

        <span className="privacypolicy__subtitle">Data Subject (or User)</span>
        <p className="privacypolicy__text">
          Data Subject is any living individual who is using our Service and is the subject of Personal Data.
        </p>

        <span className="privacypolicy__title">Information Collection and Use</span>
        <p className="privacypolicy__text">
          We collect several different types of information for various purposes to provide and improve our Service to you.
        </p>
        <span className="privacypolicy__posttitle">Types of Data Collected</span>
        <span className="privacypolicy__subtitle">Personal Data</span>
        <p className="privacypolicy__text">
          While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data").
          Personally identifiable information may include, but is not limited to:
        </p>

        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item">Email address</li>
          <li className="privacypolicy__list-item">First name and last name</li>
          <li className="privacypolicy__list-item">Cookies and Usage Data</li>
        </ul>

        <p className="privacypolicy__text">
          We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you.
          You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.
        </p>

        <span className="privacypolicy__subtitle">Usage Data</span>
        <p className="privacypolicy__text">
          We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
        </p>
        <p className="privacypolicy__text">
          This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that
          you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p className="privacypolicy__text">
          When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID,
          the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
        </p>

        <span className="privacypolicy__subtitle">Tracking &amp; Cookies Data</span>
        <p className="privacypolicy__text">
          We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
        </p>
        <p className="privacypolicy__text">
          Cookies are files with a small amount of data which may include an anonymous unique identifier.
          Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, 
          tags and scripts to collect and track information and to improve and analyse our Service.
        </p>
        <p className="privacypolicy__text">
          You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>

        <span className="privacypolicy__subtitle">Examples of Cookies we use:</span>

        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item"><span>Session Cookies. </span>We use Session Cookies to operate our Service.</li>
          <li className="privacypolicy__list-item"><span>Preference Cookies. </span>We use Preference Cookies to remember your preferences and various settings.</li>
          <li className="privacypolicy__list-item"><span>Security Cookies. </span>Security Cookies. We use Security Cookies for security purposes.</li>
        </ul>

        <span className="privacypolicy__title">Use of Data</span>
        <p className="privacypolicy__text">
          VZ Games SIA uses the collected data for various purposes:
        </p>
        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item">To provide and maintain our Service</li>
          <li className="privacypolicy__list-item">To notify you about changes to our Service</li>
          <li className="privacypolicy__list-item">To allow you to participate in interactive features of our Service when you choose to do so</li>
          <li className="privacypolicy__list-item">To provide customer support</li>
          <li className="privacypolicy__list-item">To gather analysis or valuable information so that we can improve our Service</li>
          <li className="privacypolicy__list-item">To monitor the usage of our Service</li>
          <li className="privacypolicy__list-item">To detect, prevent and address technical issues</li>
          <li className="privacypolicy__list-item">
            To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have
            already purchased or enquired about unless you have opted not to receive such information
          </li>
        </ul>

        <span className="privacypolicy__title">Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</span>
        <p className="privacypolicy__text">
          If you are from the European Economic Area (EEA), VZ Games SIA legal basis for collecting and using the personal information described in
          this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
        </p>
        <p className="privacypolicy__text">VZ Games SIA may process your Personal Data because:</p>
        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item">We need to perform a contract with you</li>
          <li className="privacypolicy__list-item">You have given us permission to do so</li>
          <li className="privacypolicy__list-item">The processing is in our legitimate interests and it is not overridden by your rights</li>
          <li className="privacypolicy__list-item">For payment processing purposes</li>
          <li className="privacypolicy__list-item">To comply with the law</li>
        </ul>


        <span className="privacypolicy__title">Retention of Data</span>
        <p className="privacypolicy__text">
          VZ Games SIA will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.
          We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to
          retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.
        </p>
        <p className="privacypolicy__text">
          VZ Games SIA will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except
          when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.
        </p>

        <span className="privacypolicy__title">Transfer of Data</span>
        <p className="privacypolicy__text">
          Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
        </p>
        <p className="privacypolicy__text">
          If you are located outside Latvia and choose to provide information to us, please note that we transfer the data, including Personal Data, to Latvia and process it there.
        </p>
        <p className="privacypolicy__text">
          Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
        </p>
        <p className="privacypolicy__text">
          VZ Games SIA will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your
          Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
        </p>

        <span className="privacypolicy__title">Disclosure of Data</span>
        <span className="privacypolicy__subtitle">Business Transaction</span>
        <p className="privacypolicy__text">
          If VZ Games SIA is involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
          We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
        </p>
        <span className="privacypolicy__subtitle">Disclosure for Law Enforcement</span>
        <p className="privacypolicy__text">
          Under certain circumstances, VZ Games SIA may be required to disclose your Personal Data if required to do so by law or
          in response to valid requests by public authorities (e.g. a court or a government agency).
        </p>
        <span className="privacypolicy__subtitle">Legal Requirements</span>
        <p className="privacypolicy__text">VZ Games SIA may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item">To comply with a legal obligation</li>
          <li className="privacypolicy__list-item">To protect and defend the rights or property of VZ Games SIA</li>
          <li className="privacypolicy__list-item">To prevent or investigate possible wrongdoing in connection with the Service</li>
          <li className="privacypolicy__list-item">To protect the personal safety of users of the Service or the public</li>
          <li className="privacypolicy__list-item">To protect against legal liability</li>
        </ul>


        <span className="privacypolicy__title">Security of Data</span>
        <p className="privacypolicy__text">
          The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure.
          While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
        </p>

        <span className="privacypolicy__title">Our Policy on "Do Not Track" Signals under the California Online Protection Act (CalOPPA)</span>
        <p className="privacypolicy__text">
          We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to
          inform websites that you do not want to be tracked.
        </p>
        <p className="privacypolicy__text">You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>


        <span className="privacypolicy__title">Your Data Protection Rights under the General Data Protection Regulation (GDPR)</span>
        <p className="privacypolicy__text">
          If you are a resident of the European Economic Area (EEA), you have certain data protection rights. VZ Games SIA
          aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.
        </p>
        <p className="privacypolicy__text">
          If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
        </p>
        <p className="privacypolicy__text">
          In certain circumstances, you have the following data protection rights:
        </p>
        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item">
            <span>The right to access, update or delete the information we have on you. </span>
            Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section.
            If you are unable to perform these actions yourself, please contact us to assist you.
          </li>
          <li className="privacypolicy__list-item">
            <span>The right of rectification. </span>
            You have the right to have your information rectified if that information is inaccurate or incomplete.
          </li>
          <li className="privacypolicy__list-item"><span>The right to object. </span>You have the right to object to our processing of your Personal Data.</li>
          <li className="privacypolicy__list-item"><span>The right of restriction. </span>You have the right to request that we restrict the processing of your personal information.</li>
          <li className="privacypolicy__list-item">
            <span>The right to data portability. </span>
            You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.
          </li>
          <li className="privacypolicy__list-item">
            <span>The right to withdraw consent. </span>
            You also have the right to withdraw your consent at any time where VZ Games SIA relied on your consent to process your personal information.
          </li> 
        </ul>
        <p className="privacypolicy__text">Please note that we may ask you to verify your identity before responding to such requests.</p>
        <p className="privacypolicy__text">
          You have the right to complain to a Data Protection Authority about our collection and use of your Personal
          Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
        </p>

        <span className="privacypolicy__title">Service Providers</span>
        <p className="privacypolicy__text">
          We may employ third party companies and individuals to facilitate our Service ("Service Providers"),
          provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
        </p>
        <p className="privacypolicy__text">
          These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
        </p>
        <span className="privacypolicy__subtitle">Analytics</span>
        <p className="privacypolicy__text">We may use third-party Service Providers to monitor and analyse the use of our Service.</p>
        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item">
            <span>Google Analytics </span>
            <p className="privacypolicy__text">
              Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service.
              This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.
            </p>
            <p className="privacypolicy__text">
              For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <span>https://policies.google.com/privacy?hl=en</span>
            </p>
          </li>
          <li className="privacypolicy__list-item">
            <span>Unity Analytics </span>
            <p className="privacypolicy__text">Unity Analytics is provided by Unity Technologies.</p>
            <p className="privacypolicy__text">
              For more information on what type of information Unity Analytics collects, please visit their Privacy Policy page: <span>https://unity3d.com/legal/privacy-policy</span>
            </p>
          </li>
          <li className="privacypolicy__list-item">
            <span>GameAnalytics </span>
            <p className="privacypolicy__text">GameAnalytics is provided by GameAnalytics</p>
            <p className="privacypolicy__text">
              For more information on what type of information GameAnalytics collects, please visit their Privacy Policy page: <span>https://gameanalytics.com/privacy</span>
            </p>
          </li>
        </ul>
        <span className="privacypolicy__subtitle">Payments</span>
        <p className="privacypolicy__text">
          We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).
        </p>
        <p className="privacypolicy__text">
          We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal
          information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council,
          which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
        </p>
        <p className="privacypolicy__text">
          The payment processors we work with are:
        </p>
        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item">
            <span>Xsolla </span>
            <p className="privacypolicy__text">
              Their Privacy Policy can be viewed at <span>https://xsolla.com/privacypolicy</span>
            </p>
          </li>
          <li className="privacypolicy__list-item">
            <span>Google Play In-App Payments </span>
            <p className="privacypolicy__text">
              Their Privacy Policy can be viewed at <span>https://www.google.com/policies/privacy/</span>
            </p>
          </li>
        </ul>

        <span className="privacypolicy__title">Links to Other Sites</span>
        <p className="privacypolicy__text">
          Our Service may contain links to other sites that are not operated by us.
          If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
        </p>
        <p className="privacypolicy__text">
          We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>

        <span className="privacypolicy__title">Children's Privacy</span>
        <p className="privacypolicy__text">Our Service does not address anyone under the age of 18 ("Children").</p>
        <p className="privacypolicy__text">
          We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that
          your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification
          of parental consent, we take steps to remove that information from our servers.
        </p>

        <span className="privacypolicy__title">Changes to This Privacy Policy</span>
        <p className="privacypolicy__text">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
        <p className="privacypolicy__text">
          We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
        </p>
        <p className="privacypolicy__text">
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>
          
        <span className="privacypolicy__title">Contact Us</span>
        <p className="privacypolicy__text">If you have any questions about this Privacy Policy, please contact us:</p>
        <ul className="privacypolicy__list">
          <li className="privacypolicy__list-item">By email: <span>info@hashrush.com</span></li>
        </ul>

      </div>
    </div>
  );
};

export default PrivacyPolicyContent;